### ISSUE TITLE
Error with wizard on 0.7.1

### ISSUE THREAD

**Issue by gassius** [phpro/soap-client#150]
This is probably related to issue #147  

After update:
```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating phpro/soap-client (0.7.0 => 0.7.1): Downloading (100%)  
```

```
./vendor/bin/soap-client wizard
PHP Fatal error:  Uncaught TypeError: Return value of Phpro\SoapClient\Console\Command\GenerateClassmapCommand::configure() must be an instance of Phpro\SoapClient\Console\Command\void, none returned in /vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateClassmapCommand.php:69
Stack trace:
#0 /vendor/symfony/console/Command/Command.php(77): Phpro\SoapClient\Console\Command\GenerateClassmapCommand->configure()
#1 /vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateClassmapCommand.php(50): Symfony\Component\Console\Command\Command->__construct()
#2 /vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Application.php(38): Phpro\SoapClient\Console\Command\GenerateClassmapCommand->__construct(Object(Phpro\SoapClient\Util\Filesystem))
#3 /vendor/symfony/console/Application.php(1219): Phpro\SoapClient\Console\Application->getDefaultCommands()
#4 / in /vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateClassmapCommand.php on line 69
```

**Comment by janvernieuwe** [comment]
I'll take a look at this and re-test with php7.0 to be sure

**Comment by janvernieuwe** [comment]
I created the 7.2 release where I retested the wizard on 7.0.
If you experience any more issues, please let us know!

**Comment by gassius** [comment]
Can confirm is working now.

Thanks again for the quick response @janvernieuwe
