### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Phpro\SoapClient\Console\Command\GenerateConfigCommand::addNonEmptySetter()

### ISSUE THREAD

**Issue by 4n70w4** [phpro/soap-client#233]
### Bug Report

phpro/soap-client (v1.0.1)

#### Current behavior

```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Phpro\SoapClient\Console\Command\GenerateConfigCommand::addNonEmptySetter() must be of the type string, null given, called in /app/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateConfigCommand.php on line 79 and defined in /app/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateConfigCommand.php:100
Stack trace:
#0 /app/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateConfigCommand.php(79): Phpro\SoapClient\Console\Command\GenerateConfigCommand->addNonEmptySetter(Object(Phpro\SoapClient\CodeGenerator\Context\ConfigContext), 'setClientNamesp...', NULL)
#1 /app/vendor/symfony/console/Command/Command.php(255): Phpro\SoapClient\Console\Command\GenerateConfigCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /app/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/WizardCommand.php(48): Symfony\Component\Console\Command\Command in /app/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateConfigCommand.php on line 100
```

#### How to reproduce

`./vendor/bin/soap-client wizard`

` Namespace for your client:`

Empty namespace and press enter.

#### Expected behavior

Re-enter the namespace or use the default value.

**Comment by janvernieuwe** [comment]
I tried to reproduce this, but when not entering a value, it kepth on asking me.

![image](https://user-images.githubusercontent.com/7813447/56423101-d50ef380-62aa-11e9-92b6-28ac6a23d5bd.png)

Do you get other behaviour?

**Comment by 4n70w4** [comment]
The same if not enter Wsdl location:

`./vendor/bin/soap-client wizard`

 ```
Where would you like to store your config file? [config/soap-client.php]:
 >


 Wsdl location (URL or path to file):
 >

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Phpro\SoapClient\CodeGenerator\Context\ConfigContext::setWsdl() must be of the type string, null given, called in /app/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateConfigCommand.php on line 67 and defined in /app/vendor/phpro/soap-client/src/Phpro/SoapClient/CodeGenerator/Context/ConfigContext.php:51
Stack trace:
#0 /app/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/GenerateConfigCommand.php(67): Phpro\SoapClient\CodeGenerator\Context\ConfigContext->setWsdl(NULL)
#1 /app/vendor/symfony/console/Command/Command.php(255): Phpro\SoapClient\Console\Command\GenerateConfigCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /app/vendor/phpro/soap-client/src/Phpro/SoapClient/Console/Command/WizardCommand.php(48): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput in /app/vendor/phpro/soap-client/src/Phpro/SoapClient/CodeGenerator/Context/ConfigContext.php on line 51
```


`composer info`

```
aws/aws-sdk-php                       3.91.4             AWS SDK for PHP - Use Amazon Web Services in your PHP project
barryvdh/laravel-debugbar             v3.2.3             PHP Debugbar integration for Laravel
barryvdh/laravel-ide-helper           v2.6.2             Laravel IDE Helper, generates correct PHPDocs for all Facade classes, to improve auto-completion.
barryvdh/reflection-docblock          v2.0.6
beyondcode/laravel-dump-server        1.2.2              Symfony Var-Dump Server for Laravel
cakephp/chronos                       1.2.4              A simple API extension for DateTime.
cendekia/nova-setting-tool            v0.0.3             An app setting manager tool for laravel nova
clue/stream-filter                    v1.4.1             A simple and modern approach to stream filtering in PHP
composer/ca-bundle                    1.1.4              Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/composer                     1.8.5              Composer helps you declare, manage and install dependencies of PHP projects, ensuring you have the ...
composer/semver                       1.5.0              Semver library that offers utilities, version constraint parsing and validation.
composer/spdx-licenses                1.5.1              SPDX licenses list and validation library.
composer/xdebug-handler               1.3.2              Restarts a process without xdebug.
coraxster/flysystem-aws-s3-v3-minio   1.0.16             Flysystem adapter for the AWS S3 SDK v3.x, forked for minio support
davidpiesse/nova-phpinfo              0.0.2              Display PHPInfo data
dillingham/nova-button                1.0.4              Nova button package
dnoegel/php-xdg-base-dir              0.1                implementation of xdg base directory specification for php
docker-php/docker-php                 v2.0.0             A Docker PHP client
docker-php/docker-php-api             v4.1.36.1          Docker API generated files from OpenAPI Specification
doctrine/cache                        v1.8.0             Caching library offering an object-oriented API for many cache backends
doctrine/dbal                         v2.9.2             Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection...
doctrine/event-manager                v1.0.0             Doctrine Event Manager component
doctrine/inflector                    v1.3.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.2.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                        v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
dragonmantank/cron-expression         v2.3.0             CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
egulias/email-validator               2.1.7              A library for validating emails against several RFCs
erusev/parsedown                      1.7.3              Parser for Markdown.
facebook/webdriver                    1.6.0              A PHP client for Selenium WebDriver
fideloper/proxy                       4.1.0              Set trusted proxies for Laravel
filp/whoops                           2.3.1              php error handling for cool kids
firebase/php-jwt                      v5.0.0             A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current s...
fzaninotto/faker                      v1.8.0             Faker is a PHP library that generates fake data for you.
google/apiclient                      v2.2.2             Client library for Google APIs
google/apiclient-services             v0.93              Client library for Google APIs
google/auth                           v1.4.0             Google Auth Library for PHP
graham-campbell/manager               v4.2.1             Manager Provides Some Manager Functionality For Laravel 5
guzzlehttp/guzzle                     6.3.3              Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1             Guzzle promises library
guzzlehttp/psr7                       1.5.2              PSR-7 message implementation that also provides common utility methods
hamcrest/hamcrest-php                 v2.0.0             This is the PHP port of Hamcrest Matchers
hashids/hashids                       3.0.0              Generate short, unique, non-sequential ids (like YouTube and Bitly) from numbers
inspheric/nova-email-field            v1.41              A Laravel Nova email field.
inspheric/nova-indicator-field        v1.2               A Laravel Nova indicator field.
jakub-onderka/php-console-color       v0.2
jakub-onderka/php-console-highlighter v0.4               Highlight PHP code in terminal
jane-php/json-schema-runtime          v4.2.0             Jane runtime Library
jane-php/open-api-runtime             v4.2.0             Jane OpenAPI Runtime Library, dependencies and utility class for a library generated by jane/openapi
jenssegers/date                       v3.5.0             A date library to help you work with dates in different languages
joedixon/laravel-translation          v0.1.4             A tool for managing all of your Laravel translations
joedixon/nova-translation             v0.1.1             A Laravel Nova tool.
justinrainbow/json-schema             5.2.8              A library to validate a json schema.
larabug/nova-larabug-tool             0.0.2              A Laravel Nova tool.
laravel/dusk                          v5.0.3             Laravel Dusk provides simple end-to-end testing and browser automation.
laravel/framework                     v5.8.11            The Laravel Framework.
laravel/nova                          dev-master ddd6c3d A wonderful administration interface for Laravel.
laravel/telescope                     v2.0.4             An elegant debug assistant for the Laravel framework.
laravel/tinker                        v1.0.8             Powerful REPL for the Laravel framework.
league/flysystem                      1.0.51             Filesystem abstraction: Many filesystems, one API.
league/uri                            5.3.0              URI manipulation library
league/uri-components                 1.8.2              URI components manipulation library
league/uri-hostname-parser            1.1.1              ICANN base hostname parsing implemented in PHP.
league/uri-interfaces                 1.1.1              Common interface for URI representation
league/uri-manipulations              1.5.0              URI manipulation library
league/uri-parser                     1.4.1              userland URI parser RFC 3986 compliant
league/uri-schemes                    1.2.1              URI manipulation library
markbaker/complex                     1.4.7              PHP Class for working with complex numbers
markbaker/matrix                      1.1.4              PHP Class for working with matrices
maximebf/debugbar                     v1.15.0            Debug bar in the browser for php application
mockery/mockery                       1.2.2              Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                       1.24.0             Sends your logs to files, sockets, inboxes, databases and various web services
moontoast/math                        1.1.2              A mathematics library, providing functionality for large numbers
mtdowling/jmespath.php                2.4.0              Declaratively specify how to extract elements from a JSON document
myclabs/deep-copy                     1.9.1              Create deep copies (clones) of your objects
nesbot/carbon                         2.16.3             A simple API extension for DateTime.
nikic/php-parser                      v4.2.1             A PHP parser written in PHP
nunomaduro/collision                  v2.1.1             Cli error handling for console/command-line PHP applications.
opis/closure                          3.1.6              A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
paragonie/random_compat               v9.99.99           PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                      1.0.3              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                       2.0.1              Library for handling version information and constraints
php-http/client-common                1.9.1              Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                    1.6.1              Finds installed HTTPlug implementations and PSR-7 message factories
php-http/httplug                      v1.1.0             HTTPlug, the HTTP client abstraction for PHP
php-http/message                      1.7.2              HTTP Message related tools
php-http/message-factory              v1.0.2             Factory interfaces for PSR-7 HTTP Message
php-http/multipart-stream-builder     1.0.0              A builder class that help you create a multipart stream
php-http/promise                      v1.0.0             Promise used for asynchronous HTTP requests
php-http/socket-client                v1.4.1             Socket client for PHP-HTTP
php-jsonpointer/php-jsonpointer       v3.0.2             Implementation of JSON Pointer (http://tools.ietf.org/html/rfc6901)
phpdocumentor/reflection-common       1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     4.3.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retri...
phpdocumentor/type-resolver           0.4.0
phpoffice/phpspreadsheet              1.6.0              PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpoption/phpoption                   1.5.0              Option Type for PHP
phpro/soap-client                     v1.0.1             A general purpose SoapClient library
phpseclib/phpseclib                   2.0.15             PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
phpspec/prophecy                      1.8.0              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             6.1.4              Library that provides collection, processing, and rendering functionality for PHP code coverage inf...
phpunit/php-file-iterator             2.0.2              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1              Simple template engine.
phpunit/php-timer                     2.1.1              Utility class for timing
phpunit/php-token-stream              3.0.1              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       7.5.8              The PHP Unit Testing framework.
psr/cache                             1.0.1              Common interface for caching libraries
psr/container                         1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                      1.0.1              Common interface for HTTP messages
psr/log                               1.1.0              Common interface for logging libraries
psr/simple-cache                      1.0.1              Common interfaces for simple caching
psy/psysh                             v0.9.9             An interactive shell for modern PHP.
ralouphie/getallheaders               2.0.5              A polyfill for getallheaders.
ramsey/uuid                           3.8.0              Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universall...
sebastian/code-unit-reverse-lookup    1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator                  3.0.2              Provides the functionality to compare PHP values for equality
sebastian/diff                        3.0.2              Diff implementation
sebastian/environment                 4.1.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state                2.0.0              Snapshotting of global state
sebastian/object-enumerator           3.0.3              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector            1.1.1              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context           3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations         2.0.1              Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
seld/jsonlint                         1.7.1              JSON Linter
seld/phar-utils                       1.0.1              PHAR file format utilities, for when PHP phars you up
spatie/once                           1.1.0              A magic memoization function
swiftmailer/swiftmailer               v6.2.0             Swiftmailer, free feature-rich PHP mailer
symfony/console                       v4.2.5             Symfony Console Component
symfony/contracts                     v1.0.2             A set of abstractions extracted out of the Symfony components
symfony/css-selector                  v4.2.5             Symfony CssSelector Component
symfony/debug                         v4.2.5             Symfony Debug Component
symfony/event-dispatcher              v4.2.5             Symfony EventDispatcher Component
symfony/filesystem                    v4.2.5             Symfony Filesystem Component
symfony/finder                        v4.2.5             Symfony Finder Component
symfony/http-foundation               v4.2.5             Symfony HttpFoundation Component
symfony/http-kernel                   v4.2.5             Symfony HttpKernel Component
symfony/options-resolver              v4.2.5             Symfony OptionsResolver Component
symfony/polyfill-ctype                v1.11.0            Symfony polyfill for ctype functions
symfony/polyfill-iconv                v1.11.0            Symfony polyfill for the Iconv extension
symfony/polyfill-intl-idn             v1.11.0            Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring             v1.11.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                v1.11.0            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                       v4.2.5             Symfony Process Component
symfony/routing                       v4.2.5             Symfony Routing Component
symfony/serializer                    v4.2.5             Symfony Serializer Component
symfony/translation                   v4.2.5             Symfony Translation Component
symfony/var-dumper                    v4.2.5             Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v4.2.5             Symfony Yaml Component
theseer/tokenizer                     1.1.2              A small library for converting tokenized PHP source code into XML and potentially other formats
tijsverkoyen/css-to-inline-styles     2.2.1              CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files wit...
unisharp/laravel-settings             2.0.3              Persistent settings manager for laravel, translations are supported.
vinkla/hashids                        5.2.0              A Hashids bridge for Laravel
vlucas/phpdotenv                      v3.3.3             Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
vnn/wordpress-rest-api-client         1.2.0
webmozart/assert                      1.4.0              Assertions to validate method input/output with nice error messages.
zendframework/zend-code               3.3.1              provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-eventmanager       3.2.1              Trigger and listen to events within a PHP application
```

**Comment by janvernieuwe** [comment]
Hmm i tried to reproduce this with lowest and highest dependencies, but I was unable to reproduce this.
What PHP version are you using?

**Comment by 4n70w4** [comment]
`php -v`

```
PHP 7.1.27 (cli) (built: Mar  7 2019 13:11:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.27, Copyright (c) 1999-2018, by Zend Technologies
```

docker image bitnami/laravel:5-debian-9 (b4e548c1781f)
https://hub.docker.com/r/bitnami/laravel

**Comment by janvernieuwe** [comment]
Tried it with 7.1, still had to enter a value.
Maybe it's an issue with the docker image then :thinking:

**Comment by janvernieuwe** [comment]
Managed to reproduce the issue.
It only occurs when symfony console `^4.0` is used. In 4.0 there is no more default validation on the questions, and you need to write your own validators for console questions.

Fix in PR.
