### ISSUE TITLE
Wizard - Call to a member function setNamespaceName() on bool

### ISSUE THREAD

**Issue by DamienDub** [phpro/soap-client#258]
### Bug Report

OS: Windows 10
PHP version: 7.3.9
Zend code version: 3.4.0
soap-client version: 1.0.4

#### Summary

When using the wizard with [this WSDL file](https://github.com/phpro/soap-client/blob/master/test/fixtures/wsdl/weather-ws.wsdl), I get this exception:
```
PHP Fatal error:  Uncaught Error: Call to a member function setNamespaceName() on bool in C:\Users\d.dubernet\workspace\soap-client\src\Phpro\SoapClient\CodeGenerator\TypeGenerator.php:43
Stack trace:
#0 C:\Users\d.dubernet\workspace\soap-client\src\Phpro\SoapClient\Console\Command\GenerateTypesCommand.php(199): Phpro\SoapClient\CodeGenerator\TypeGenerator->generate(Object(Zend\Code\Generator\FileGenerator), Object(Phpro\SoapClient\CodeGenerator\Model\Type))
#1 C:\Users\d.dubernet\workspace\soap-client\src\Phpro\SoapClient\Console\Command\GenerateTypesCommand.php(130): Phpro\SoapClient\Console\Command\GenerateTypesCommand->generateType(Object(Zend\Code\Generator\FileGenerator), Object(Phpro\SoapClient\CodeGenerator\TypeGenerator), Object(Phpro\SoapClient\CodeGenerator\Model\Type), Object(SplFileInfo))
#2 C:\Users\d.dubernet\workspace\soap-client\src\Phpro\SoapClient\Console\Command\GenerateTypesCommand.php(88): Phpro\SoapClient\Console\Command\GenerateTypesCommand->handleType(Object(Phpro\SoapClient\CodeGenerator\TypeGenerator in C:\Users\d.dubernet\workspace\soap-client\src\Phpro\SoapClient\CodeGenerator\TypeGenerator.php on line 43
```

In ClientGenerator and TypeGenerator, if I replace this line:
```
$class = $file->getClass() ?? new ClassGenerator();
```
with this line:
```
$class = new ClassGenerator();
```

The generation seems to work fine. Did I miss something?

**Comment by janvernieuwe** [comment]
Hi @DamienDub ,

Thanks for reporting this, I'm able to reproduce it and working on a fix.
It appears a return type in the docblocks of zend-code is also incorrect.

Will fix this asap (today)
